[project]
name = "excel-fund-two"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.121.2",
    "jinja2>=3.1.6",
    "openpyxl>=3.1.5",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.38.0",
]
